# This is a basic workflow that is manually triggered

name: AI issue workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 issue_comment:
    types: [created]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    timeout-minutes: 20
    if: github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@great')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Post a comment to the issue
    - name: Post greeting comment
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Hello @${{ github.event.comment.user.login }}'
          })
